[creator]
type = "user"
id = 2912484262

[codegen]
typescript = false
style = "nested"
strip_extensions = false
content = false

[inputs.assets]
path = "assets/**/*"
output_path = "packages/assets/src"
