[tools]
"github:JohnnyMorganz/StyLua" = "latest"
"github:Kampfkarren/selene" = "latest"
"github:jackTabsCode/asphalt" = "latest"
"github:luau-lang/lute" = "latest"
"github:pesde-pkg/pesde" = "latest"
"github:rojo-rbx/rojo" = "latest"
"github:seaofvoices/darklua" = "latest"
just = "latest"
mprocs = "latest"
